version: "3"

services:
  djangoapp:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume
    networks:
      - nginx_network

  nginx:
    image: pagespeed/nginx-pagespeed:latest
    platform: linux/x86_64
    ports:
      - 80:80
    volumes:
      - .nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/opt/services/djangoapp/static  # <-- bind the static volume
      - media_volume:/opt/services/djangoapp/media  # <-- bind the media volume
    depends_on:
      - djangoapp
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume