#Sample CD file
name: Build django app

on: 
  push:
    branches: 
        - 'feature/add_actions'
    tags: [ v* ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: personalwebsite
  USERNAME: kjellzijlemaker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ARTIFACT_HOST }}
          username: ${{ secrets.ARTIFACT_USERNAME }}
          key: ${{ secrets.ARTIFACT_SSH_KEY }}
          port: 22
          script: |
            cd personalwebsite
            git checkout ${{ github.ref }}
            git pull origin ${{ github.ref }}
            docker login ${{ env.REGISTRY }} --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_VM_TOKEN }}

            docker-compose -f docker-compose.${{ github.ref }}.yml pull 
        

            
            