name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install black
        run: |
          pip install black==21.5b1
          pip install pytest==6.2.4

      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./personalwebsite"
          jupyter: true
          version: "21.5b1"

      - name: Run tests
        run: |
          pytest ./personalwebsite/tests