#Sample CD file
name: Build django app

on: 
  push:
    branches: 
        - 'feature/add_actions'
    tags: [ v* ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: personalwebsite
  USERNAME: kjellzijlemaker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Docker Compose Action
      #   uses: isbang/compose-action@v1.5.1
      #   with:
      #     compose-file: "docker-compose.yml"


      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        

  # deploy:
  #   runs-on: ubuntu-latest
  #   # needs: build
  #   steps:

  #     - name: Run Docker
  #     - name: Run docker compose
  #       uses: jawher/action-hcloud@v1.37.0
  #       env:
  #         HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
  #       with:
  #         args: docker-compose up -d


            
            