#Sample CD file
name: Deploy to server or Storage Box
on: 
  push:
    branches: 
        - 'feature/add_actions'
    tags: [ v* ]
    
env:
  REGISTRY: docker.io
  IMAGE_NAME: personalwebsite
  USERNAME: kjellzijlemaker

jobs:
