name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install black
        run: |
          pip install black==21.5b1
          pip install pytest==6.2.4

      - name: Run black
        run: |
          black . --check
      
      - name: show directory
        run: |
          ls -la

      - name: Run tests
        run: |
          kjellzijlemaker/manage.py test kjellzijlemaker/personalwebsite/tests