name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install django and black
        run: |
          pip install django==3.2.4
          pip install black==21.5b2
        
      - name: Run black
        run: |
          black . --check
      
      - name: show directory
        run: |
          ls -la

      - name: Run tests
        run: |
          kjellzijlemaker/manage.py test kjellzijlemaker/personalwebsite/tests