name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry and run poetry install
        run: |
          pip install poetry==1.6.1
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
          

      - name: Run black
        run: |
          black . --check
      
      - name: show directory
        run: |
          ls -la

      - name: Run tests
        run: |
          kjellzijlemaker/manage.py test kjellzijlemaker/personalwebsite/tests