#Sample CD file
name: Build and Deploy personal website

on: 
  push:
    branches: 
        - 'main'
    tags: [ v* ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: personalwebsite
  USERNAME: kjellzijlemaker

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/build
        with: 
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_VM_TOKEN }}
          REGISTRY: ${{ env.REGISTRY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: ./.github/workflows/tag
        with: 
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_VM_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: tag
    concurrency: production
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/deploy
        with: 
          ARTIFACT_HOST: ${{ secrets.ARTIFACT_HOST }}
          ARTIFACT_USERNAME: ${{ secrets.ARTIFACT_USERNAME }}
          ARTIFACT_SSH_KEY: ${{ secrets.ARTIFACT_SSH_KEY }}
          REGISTRY: ${{ env.REGISTRY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_VM_TOKEN: ${{ secrets.DOCKERHUB_VM_TOKEN }}
          
      - name: Minor version for each merge
        id: taggerFinal
        uses: cn@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          WITH_V: true